import type { Metadata } from "next";
import { Inter, Gravitas_One  } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets:['latin'] });
// const gO = Gravitas_One({ subsets:['latin'] })

export const metadata: Metadata = {
  title: "Recheck",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}>
          <Toaster position={"top-right"} />
            {children}
      </body>
    </html>
  );
}
